modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="forever_production_monitor"
version="5.2.0-SNAPSHOT"
displayName="Forever Production Monitor"
description='''AE2 monitoring and diagnostics with production and storage statistics, alarms, a Mini HUD, Missing Channel tools and an interactive 3D Network Map.'''
authors="Timo"

[[dependencies.forever_production_monitor]]
modId="neoforge"
type="required"
versionRange="[21.1.249,)"
ordering="NONE"
side="BOTH"

[[dependencies.forever_production_monitor]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.forever_production_monitor]]
modId="ae2"
type="required"
versionRange="[19.2.17,20)"
ordering="AFTER"
side="BOTH"

[[dependencies.forever_production_monitor]]
modId="curios"
type="required"
versionRange="[9.5.1,)"
ordering="AFTER"
side="BOTH"
